name: Branch Build and Push

on:
  push:
    branches: '**'

jobs:
  docker-build-and-push:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Set the branch and commit env var
        id: set_branch_commit_vars
        run: |
          echo "branch_var=${GITHUB_REF#refs/heads/}" | tr / _ | tee -a $GITHUB_ENV
          echo "commit_var=$(echo ${GITHUB_SHA} | cut -c1-7)" | tee -a $GITHUB_ENV
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./docker/
          push: true
          tags: r0cc4rd0/nextcloud-lh-bak:${{ env.commit_var }}, r0cc4rd0/nextcloud-lh-bak:${{ env.branch_var }}-latest
          no-cache: false
          cache-from: type=registry,ref=r0cc4rd0/nextcloud-lh-bak:${{ env.branch_var }}-latest
          cache-to: type=inline
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
